server:
  port: 9097

spring:
  application:
    name: mailer-service

  # Mail configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${username}
    password: ${password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Kafka configuration
  kafka:
    bootstrap-servers: ${kafka_bootstrap_servers}
    username: ${kafka_username}
    password: ${KAFKA_PASSWORD}
    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas.config: >
          org.apache.kafka.common.security.scram.ScramLoginModule required
          username="${kafka_username}"
          password="${KAFKA_PASSWORD}";
    consumer:
      group-id: mailer-group-dev
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.mailer.event.UserRegisteredEvent

# Twilio configuration
twilio:
  account-sid: ${TWILIO_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${phone-number}