server:
  port: 9089

spring:
  application:
    name: mailer-service

  # Mail configuration (spring ke andar)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${username}
    password: ${password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Kafka configuration (ISE BHI SPRING KE ANDAR HONA CHAHIYE)
  kafka:
    bootstrap-servers: localhost:9092
    username: ${kafka_username}
    password: ${KAFKA_PASSWORD}
    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${kafka_username}" password="${KAFKA_PASSWORD}";'
    consumer:
      group-id: mailer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.mailer.event.UserRegisteredEvent

# Twilio (Ye spring ke bahar rahega, top level par)
twilio:
  account-sid: ${TWILIO_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${phone-number}

resend:
  api-key: ${RESEND_API_KEY}
  sender-email: ${RESEND_SENDER_EMAIL:onboarding@resend.dev}

# ================================
# LOGGING
# ================================
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%-5level) [%X{requestId}] [trace_id=%X{trace_id}] [%X{clientIp}] %clr([%thread]){magenta} %clr(%logger{36}){cyan} : %msg%n%wEx{5}"
  level:
    root: INFO
    org.hibernate.orm.connections.pooling: ERROR
